/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-2',
  aws_cognito_identity_pool_id: 'us-east-2:7d061262-a05d-4dc1-9a99-4497b7dd8884',
  aws_cognito_region: 'us-east-2',
  aws_user_pools_id: 'us-east-2_s5BKSfUEe',
  aws_user_pools_web_client_id: '3bvck6usvli3aa758ppvcv60m4',
  oauth: {},
  aws_cognito_login_mechanism: [],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
};

export default awsmobile;
