/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-2',
  aws_cognito_identity_pool_id: 'us-east-2:83eb0e4f-66f8-4d86-af15-206affc6da78',
  aws_cognito_region: 'us-east-2',
  aws_user_pools_id: 'us-east-2_yoBfrxLnu',
  aws_user_pools_web_client_id: 'j4lc6c2p5s0n09i5kbojfsnlg',
  oauth: {},
  aws_cognito_login_mechanism: [],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
};

export default awsmobile;
