# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  PACT_BROKER_BASE_URL: https://c4cneu.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
  PACT_PACTICIPANT: jpal-frontend
  GIT_COMMIT: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run check
      - run: npm run build
      - run: npm run test
      - run: npm run test:pact
      - run: npm run cy:ci
      - run: docker pull pactfoundation/pact-cli:latest
      - name: Publish pact tagged with branch name
        run: pact-broker publish ./pact/pacts \ 
                 --consumer-app-version=${GIT_COMMIT} \
                 --broker-base-url=${PACT_BROKER_BASE_URL} \
                 --broker-token=${PACT_BROKER_TOKEN} \
                 --tag ${GITHUB_REF:11}

  can-i-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: docker pull pactfoundation/pact-cli:latest
      - name: Can I deploy?
        run: |
          docker run --rm \
              pactfoundation/pact-cli:latest \
              broker can-i-deploy \
              --broker-base-url=${PACT_BROKER_BASE_URL} \
              --broker-token ${PACT_BROKER_TOKEN} \
              --pacticipant ${PACT_PACTICIPANT} \
              --version ${GIT_COMMIT} \
              --to prod
      
  #TODO: write a real deploy script
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: can-i-deploy
    steps:
      - uses: actions/checkout@v2
      - run: docker pull pactfoundation/pact-cli:latest
      - name: Tag version as prod
        run: |
          docker run --rm \
              pactfoundation/pact-cli:latest \
              broker create-version-tag \
              --broker-base-url=${PACT_BROKER_BASE_URL} \
              --broker-token ${PACT_BROKER_TOKEN} \
              --pacticipant ${PACT_PACTICIPANT} \
              --version ${GIT_COMMIT} \
              --tag prod   